[2024-02-10T03:55:34.182+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_api_dag.get_weather_data manual__2024-02-10T03:50:31.726686+00:00 [queued]>
[2024-02-10T03:55:34.188+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_api_dag.get_weather_data manual__2024-02-10T03:50:31.726686+00:00 [queued]>
[2024-02-10T03:55:34.189+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-02-10T03:55:34.203+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-02-10 03:50:31.726686+00:00
[2024-02-10T03:55:34.209+0000] {standard_task_runner.py:60} INFO - Started process 3713 to run task
[2024-02-10T03:55:34.211+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_api_dag', 'get_weather_data', 'manual__2024-02-10T03:50:31.726686+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/weather_api__dag.py', '--cfg-path', '/tmp/tmpyjdydq_u']
[2024-02-10T03:55:34.213+0000] {standard_task_runner.py:88} INFO - Job 214: Subtask get_weather_data
[2024-02-10T03:55:34.252+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_api_dag.get_weather_data manual__2024-02-10T03:50:31.726686+00:00 [running]> on host c5d03f501d38
[2024-02-10T03:55:34.323+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='ahaonezero@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_api_dag' AIRFLOW_CTX_TASK_ID='get_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T03:50:31.726686+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-10T03:50:31.726686+00:00'
[2024-02-10T03:55:34.334+0000] {logging_mixin.py:188} INFO - ***
[2024-02-10T03:55:34.335+0000] {logging_mixin.py:188} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7fb765bf91c0>, 'dag': <DAG: weather_api_dag>, 'dag_run': <DagRun weather_api_dag @ 2024-02-10 03:50:31.726686+00:00: manual__2024-02-10T03:50:31.726686+00:00, state:running, queued_at: 2024-02-10 03:50:31.742340+00:00. externally triggered: True>, 'data_interval_end': DateTime(2024, 2, 10, 3, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2024, 2, 10, 2, 0, 0, tzinfo=Timezone('UTC')), 'ds': '2024-02-10', 'ds_nodash': '20240210', 'execution_date': <Proxy at 0x7fb759225fc0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'execution_date', DateTime(2024, 2, 10, 3, 50, 31, 726686, tzinfo=Timezone('UTC')))>, 'expanded_ti_count': None, 'inlets': [], 'logical_date': DateTime(2024, 2, 10, 3, 50, 31, 726686, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.8/site-packages/***/macros/__init__.py'>, 'next_ds': <Proxy at 0x7fb759233cc0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'next_ds', '2024-02-10')>, 'next_ds_nodash': <Proxy at 0x7fb759233d00 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'next_ds_nodash', '20240210')>, 'next_execution_date': <Proxy at 0x7fb759233d40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'next_execution_date', DateTime(2024, 2, 10, 3, 50, 31, 726686, tzinfo=Timezone('UTC')))>, 'outlets': [], 'params': {}, 'prev_data_interval_start_success': DateTime(2024, 2, 10, 2, 0, 0, tzinfo=Timezone('UTC')), 'prev_data_interval_end_success': DateTime(2024, 2, 10, 3, 0, 0, tzinfo=Timezone('UTC')), 'prev_ds': <Proxy at 0x7fb759233d80 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'prev_ds', '2024-02-10')>, 'prev_ds_nodash': <Proxy at 0x7fb759233dc0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'prev_ds_nodash', '20240210')>, 'prev_execution_date': <Proxy at 0x7fb759233e00 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'prev_execution_date', DateTime(2024, 2, 10, 3, 50, 31, 726686, tzinfo=Timezone('UTC')))>, 'prev_execution_date_success': <Proxy at 0x7fb759233e40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'prev_execution_date_success', DateTime(2024, 2, 10, 2, 0, 0, tzinfo=Timezone('UTC')))>, 'prev_start_date_success': DateTime(2024, 2, 10, 3, 0, 0, 677484, tzinfo=Timezone('UTC')), 'prev_end_date_success': DateTime(2024, 2, 10, 3, 0, 5, 75517, tzinfo=Timezone('UTC')), 'run_id': 'manual__2024-02-10T03:50:31.726686+00:00', 'task': <Task(PythonOperator): get_weather_data>, 'task_instance': <TaskInstance: weather_api_dag.get_weather_data manual__2024-02-10T03:50:31.726686+00:00 [running]>, 'task_instance_key_str': 'weather_api_dag__get_weather_data__20240210', 'test_mode': False, 'ti': <TaskInstance: weather_api_dag.get_weather_data manual__2024-02-10T03:50:31.726686+00:00 [running]>, 'tomorrow_ds': <Proxy at 0x7fb759233e80 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'tomorrow_ds', '2024-02-11')>, 'tomorrow_ds_nodash': <Proxy at 0x7fb759233ec0 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'tomorrow_ds_nodash', '20240211')>, 'triggering_dataset_events': <Proxy at 0x7fb7592d0e00 with factory <function _get_template_context.<locals>.get_triggering_events at 0x7fb7592b7b80>>, 'ts': '2024-02-10T03:50:31.726686+00:00', 'ts_nodash': '20240210T035031', 'ts_nodash_with_tz': '20240210T035031.726686+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': <Proxy at 0x7fb759233f00 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'yesterday_ds', '2024-02-09')>, 'yesterday_ds_nodash': <Proxy at 0x7fb759233f40 with factory functools.partial(<function lazy_mapping_from_context.<locals>._deprecated_proxy_factory at 0x7fb7592b7700>, 'yesterday_ds_nodash', '20240209')>, 'templates_dict': None}
[2024-02-10T03:55:34.337+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-02-10T03:55:34.338+0000] {logging_mixin.py:188} INFO - 2024-02-10T03:50:31.726686+00:00
[2024-02-10T03:55:34.410+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weather_api__dag.py", line 26, in _get_weather_data
    print(response.uri)
AttributeError: 'Response' object has no attribute 'uri'
[2024-02-10T03:55:34.417+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=weather_api_dag, task_id=get_weather_data, execution_date=20240210T035031, start_date=20240210T035534, end_date=20240210T035534
[2024-02-10T03:55:34.429+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-02-10T03:55:34.429+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-02-10T03:55:34.430+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-02-10T03:55:34.431+0000] {email.py:281} INFO - Sent an alert email to ['ahaonezero@gmail.com']
[2024-02-10T03:55:34.466+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 214 for task get_weather_data ('Response' object has no attribute 'uri'; 3713)
[2024-02-10T03:55:34.506+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-10T03:55:34.525+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
